source 'https://github.com/CocoaPods/Specs.git'

target "SeaFoamClient" do

platform :ios, '8.0'

pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack'
pod 'JSQSystemSoundPlayer'
pod 'JSQMessagesViewController'

end
